#-------------------------------
# Site Settings
title: raumberger.dev
logo: # You can add own logo. For example '/images/logo.png'.
description: My personal blog


#-------------------------------
# Navigation Settings
menu-settings:
  menu-items:
    - title: 'Home'
      url: '/'
    - title: 'About'
      url: '/about/'
    - title: 'Contact Me'
      url: '/contact/'


#-------------------------------
# Author Settings
author:
  name: Richard Raumberger
  avatar: '/images/background.png'


#-------------------------------
# Hero Settings
hero:
  title: Richard Raumberger
  description: Software Developer and Hobby Astrophotograph
  image: '/images/background.png'


#-------------------------------
# Contact Settings
contact:
  email: xyyqawdn
  description: Feel free to reach out to me

#-------------------------------
# Footer section
social:
- {icon: "fa-brands fa-github", name: "Github", link: "https://github.com/rraumberger"}


# Example of adding a new link to the footer - {icon: "fa-brands fa-mastodon", name: "Mastodon", link: "https://mastodon.social/"}
# Other icons can be found at https://fontawesome.com/icons


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: raumberger-dev



#-------------------------------
# Newsletter
mailchimp: false # To enable the mailchimp form, use the value 'enable'. To disable the form, leave the field blank.
mailchimp-identifier: # Add your MailChimp form identifier. For example - gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp
mailchimp-button-text: Join

